### PR TITLE
react 19 stable

### PR DESCRIPTION
**Pull request by dai-shi**
Finally!

It's unfortunate that Waku isn't v1 yet.

### CODE REVIEW

**Comment by tylersayshi** [comment]
Should we keep any of our tests on canary?

**Comment by dai-shi** [comment]
> Should we keep any of our tests on canary?

I thought about it too, but we don't want to increase CI time for each PR.
I will probably create a separate PR so that we can run tests on canary manually, on demand.

**Comment by tylersayshi** [comment]
> > Should we keep any of our tests on canary?
> 
> I thought about it too, but we don't want to increase CI time for each PR. I will probably create a separate PR so that we can run tests on canary manually, on demand.

we could run a github action exclusively on main to test canary versions. 

This would mean that PRs would have the same pipeline time, but we run an additional check after it is merged to main, so we should know of issues on canary before we go go do a release. 

If it is its own CI process we can re-use the same tests too and just run the pnpm update to canary on the CI job.

I'm happy to work on a PR for this if it sounds good to you

**Comment by dai-shi** [comment]
> we could run a github action exclusively on main to test canary versions.

good idea.

> I'm happy to work on a PR for this if it sounds good to you

Yeah, please go ahead!

**Pull request merged**
