### PR TITLE
chore: switch `vite-plugin-stylex`  to `vite-plugin-stylex-dev`

### PR DESCRIPTION
**Pull request by nonzzz**
# Background

`vite-plugin-stylex-dev` has more features than `vite-plugin-stylex`, and then `vite-plugin-stylex-dev` can convert most of scense. Such as `path alias` and etc. And it can work well with vite’s internal css plugin. So i think using `vite-plugin-stylex-dev` is better.

### CODE REVIEW

**Comment by dai-shi** [comment]
@himself65

**Comment by himself65** [comment]
yeah, this guy has messaged me privately. I will check if it indeed better like say so. For now I have no particular preference for this PR since examples are just show cases, does not have better or worse

**Comment by dai-shi** [comment]
are these packages developed by different authors?

**Comment by nonzzz** [comment]
> are these packages developed by different authors?

yes,I'm one of them, They are not official plugins, but their development concepts are different, I think it's very troublesome to adapt each framework or library, So i made `vite-plugin-stylex-dev` to solve it.As the stylex team said, the official version won't be provided until the community is stable.

**Comment by dai-shi** [comment]
There will be `vite-plugin-stylex-dev2` in the future.
I think unless `vite-plugin-stylex` is really broken, we don't need to switch, and wait for the official version. Though, it might be interesting, if the new one provides a meaningful capability for Waku's show case. I'll leave it to @himself65 .

**Comment by himself65** [comment]
We have one reason to use this plugin; this plugin supports the latest stylex with the ESM module that won't break Vite

https://github.com/facebook/stylex/pull/328

**Comment by himself65** [comment]
BTW, I want to have a way to include as many plugin into our CI as possible so we can see the ecosystem compatibility

**Comment by dai-shi** [comment]
> a way to include as many plugin into our CI

You mean without explicitly adding them in examples? Would be great.

**Comment by dai-shi** [comment]
As I tried, this behaves better. Previously, the style isn't applied on the initial load (dev-only). So, I think we should merge this.

@nonzzz Would you please resolve conflicts?

**Comment by nonzzz** [comment]
@dai-shi I will resolve them :)

**Comment by nonzzz** [comment]
Resolve done.

**Pull request merged**
