### PR TITLE
fix: avoid 500 when it should not be

### LINKED ISSUE #253: url with `?a=b` will crash vercel serverless function
```shell
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: not handled","reason":{"errorType":"Error","errorMessage":"not handled","stack":["Error: not handled","    at file:///var/task/serve.js:7:11","    at file:///var/task/node_modules/waku/dist/lib/rsc/handler-prd.js:93:9","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: not handled","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:529:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

### PR DESCRIPTION
**Pull request by dai-shi**
close #253 
supersede #254

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
things interesting. In 01 example, visit `http://localhost:3000/?a=b`. Website will be at loading spinner

**Comment by dai-shi** [comment]
Can't repro. Is it vite's 504 error? How can it be fixed?

**Review by himself65 — CHANGES_REQUESTED** [review]
I think we should return 404 only if getSsrConfig returns null?

**Comment by dai-shi** [comment]
> I think we should return 404 only if getSsrConfig returns null?

When getSsrConfig returns `null`, it doesn't mean 404. It goes to the next middleware and static files might be served. Consider, for example, `/favicon.ico`.

**Pull request merged**
