### PR TITLE
waku: remove cjs build

### PR DESCRIPTION
**Pull request by dai-shi**
There was a reason to have CJS, but I think the need is already gone. So, let's try.

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
if so, we don't need swc either

**Comment by dai-shi** [comment]
why so?

**Comment by himself65** [comment]
> why so?

https://github.com/dai-shi/waku/pull/144#pullrequestreview-1696248663

**Comment by dai-shi** [comment]
Oh, you mean to use `tsc` instead of `swc`.
I'm afraid tsc is to slow for my development flow.

My desire was to use `swc` in `create-waku`. Did we miscommunicate there?

**Pull request merged**
