### PR TITLE
run tests on all node versions

### PR DESCRIPTION
**Pull request by dai-shi**
#945 wasn't enough. cc @himself65

### CODE REVIEW

**Comment by dai-shi** [comment]
Hey @cjpais, would you be able to help on this?

https://github.com/dai-shi/waku/actions/runs/11680436701/job/32523455047?pr=988

```
 FAIL  tests/buffer.test.ts > parseFormData > should handle base64 encoded content
AssertionError: expected '\u001d\ufffde\ufffdj+\ufffd' to be 'Hello, World!' // Object.is equality

Expected: "Hello, World!"
Received: "�e�j+�"
```

It fails only on Node 22.

**Review by himself65 — APPROVED** [review]
LGTM

**Review by himself65 — COMMENTED** [review]
it's undici, just check the change is from 6.7.0 to 6.7.1

**Comment by himself65** [comment]
They changed the formData implmenetation at some moment 

https://github.com/nodejs/undici/commit/5bb84bafef7421e5b8f6b93cad80c3836796aedb#diff-1ca2b01f3e34a5e04ad9a3d2d337c089326920a9c4f96edaea22ea37abe89745

**Comment by dai-shi** [comment]
Do you mean this? https://github.com/nodejs/undici/releases/tag/v6.7.1

Any idea how we can properly handle it?

**Comment by himself65** [comment]
> Do you mean this? https://github.com/nodejs/undici/releases/tag/v6.7.1
> 
> Any idea how we can properly handle it?

We can do something like

```ts
const needPolyfillPromise = parseFormData(...)
```

**Comment by himself65** [comment]
We will drop nodejs 18 after few months evetually. I think just do some check is ok

**Comment by tylersayshi** [comment]
Should dropping node 18 support happen before v1 is released? Otherwise it'll likely need to wait for a v2 given that that's a fairly significant breaking change?

**Comment by dai-shi** [comment]
node 18 will be dropped at some point, but the issue exists in node 20 too.
I hope @cjpais would take some time and come up with a conclusion.

**Pull request merged**
