### PR TITLE
update react beta

### PR DESCRIPTION
**Pull request by dai-shi**

### CODE REVIEW

**Comment by himself65** [comment]
I feel like there is a module resolution issue somewhere `var React = require('react');` is undefined

**Comment by himself65** [comment]
Ok, I debug and __SERVER_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE is in React but `__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE` is not, so at that moment, it returns react server code

**Comment by dai-shi** [comment]
Hm? Is there anything we can do then?

**Comment by himself65** [comment]
I'm bisecting to see which commit caused this

**Comment by himself65** [comment]
- 19.0.0-canary-4c12339ce-20240408 ✅
- 19.0.0-canary-adb717393-20240411 ❌

**Comment by himself65** [comment]
OK, I made some changes in the React source code, and it works well. Not sure if this is an upstream issue... But I will open a draft to react repo

**Comment by lazarv** [comment]
Hi @dai-shi! I've found this issue and related PR at React while fixing and patching up my framework.
My workaround was to register a node.js loader, where I change `react/jsx-dev-runtime` to `react/jsx-runtime` with `react-server` conditions. But I'm still working on resolving every breaking change React introduced since I created my initial version of my own framework. I was almost finished with the next version and the docs when I tried to upgrade to latest experimental React. Congrats for the release and keep up!

**Comment by himself65** [comment]
Waiting for https://github.com/facebook/react/pull/28921 a new beta release

**Comment by eps1lon** [comment]
New Beta releases are automatically published every day around 4:15pm UTC

**Pull request closed without merging**
