### PR TITLE
feat: add screenshot matching to smoke test "12_css"

### PR DESCRIPTION
**Pull request by aheissenberger**
* add the option to add a snapshot of the screen to a test
* activate screenshots for "12_css"
* add the reference screenshots for "12_css"

### CODE REVIEW

**Comment by dai-shi** [comment]
@himself65 Can you review this?

**Comment by aheissenberger** [comment]
I have no idea on how to add the missing reference screenshots for the other platforms :-(

**Comment by himself65** [comment]
> I have no idea on how to add the missing reference screenshots for the other platforms :-(

Maybe not possible or we will have to write a complex CI

**Review by himself65 — CHANGES_REQUESTED** [review]
there is a tricky thing that if we skip `windows` and `linux`, the future contributors who don't have a Mac will hard to upgrade the snapshot.

1. custom visual test in GitHub Action, to support update snapshots with all platforms.
2. using [storybook](https://storybook.js.org/docs/writing-tests/visual-testing) + [chromatic](https://www.chromatic.com/). But since they don't support testing in the framework level, so also need to make some hack.

**Comment by himself65** [comment]
For 2, I would say we separately add new fixtures and use storybook + chromatic would that be better?

**Comment by dai-shi** [comment]
Yeah, in any case, this should be a new fixture, not a smoke test on an example.
Please open a new PR.

**Pull request closed without merging**
