### PR TITLE
refactor(deploy): partykit serve

### PR DESCRIPTION
**Pull request by dai-shi**
Prior art:
- #877 
- #878 
- and many other follow-up PRs (already merged)

### CODE REVIEW

**Comment by dai-shi** [comment]
@threepointone Hi, would you be able to test and see if this really works?

**Comment by dai-shi** [comment]
@threepointone Are you around?

**Comment by threepointone** [comment]
Sorry I missed this completely, busy with cf bday week launches. I'll have a look this weekend!

**Comment by dai-shi** [comment]
Let me merge this for now.

@threepointone Please test it whenever you have time, and send PRs to fix/improve it.

**Pull request merged**
