### PR TITLE
chore(deps): update dependencies

### PR DESCRIPTION
**Pull request by dai-shi**

### CODE REVIEW

**Comment by tylersayshi** [comment]
@dai-shi would it be helpful to setup [dependabot](https://github.com/dependabot) or something similar, so you don't need to worry about doing this manually?

**Comment by dai-shi** [comment]
No, dependabot is too noisy. Doing it manually feels more comfortable as I can control the timing.

In most cases, we don't have issues. Sometimes, we do, like this one. 😄

**Comment by tylersayshi** [comment]
> No, dependabot is too noisy.

It is configurable, so we could set it to run only on certain versions, times, or whatever you would like, but otherwise no worries!

**Comment by dai-shi** [comment]
> times

Can it be like once per month for all dependencies?
I don't think I'm comfortable even with it, but just curious.

**Comment by tylersayshi** [comment]
> Can it be like once per month for all dependencies?
yep! docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

**Comment by dai-shi** [comment]
Fixing this correctly requires more work than expected. Still working on it.

**Comment by dai-shi** [comment]
`pnpm -F 42_react-tweet dev` causes this error with SSR.
This has already been the case before this PR. Correct solution is unknown. It seems related with RSC module resolution -> SSR module loading

```
TypeError: Unknown file extension ".css" for /Users/daishi/src/github-git/waku/node_modules/.pnpm/react-tweet@3.2.1_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-tweet/dist/twitter-theme/tweet-actions.module.css
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:124:36)
    at defaultLoad (node:internal/modules/esm/load:84:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Pull request merged**
