### PR TITLE
test: unit and type tests for createPages

### PR DESCRIPTION
**Pull request by pmelab**
I have not yet found a way to add type-tests for `CreatePage` and `CreateLayout`. Since the generic is on the function and not on the argument, the `path` property always resolves to `never`. I'm not sure if a test is even possible in this case. Any suggestions are welcome.

### CODE REVIEW

**Comment by dai-shi** [comment]
How about something like 403f4775 ?

**Comment by pmelab** [comment]
> How about something like [403f477](https://github.com/dai-shi/waku/commit/403f4775800eda3d9b37bed892a0f388a44a5a9c) ?

Haha, yeah obviously. I was tunnel-visioned on `ts-expect`.

**Comment by dai-shi** [comment]
Same. I thought about using `TypeEqual` first.

**Review by dai-shi — APPROVED** [review]
It looks good overall. Let me know when it's ready to merge.

**Comment by pmelab** [comment]
> It looks good overall. Let me know when it's ready to merge.

Lets go!

**Pull request merged**
