### PR TITLE
fix: stop sending ssr hydrate flag when the `--with-ssr` flag is absent

### PR DESCRIPTION
**Pull request by Aslemammad**
While working on #552 

I found out that the ci was giving hydration error while the withSSR was false. The reason was that `data-hydrate` was always true.

### CODE REVIEW

**Comment by dai-shi** [comment]
> The reason was that `data-hydrate` was always true.

That's kind of intentional. Can you help me understand the problem? How can I reproduce the bug?

**Comment by Aslemammad** [comment]
> That's kind of intentional. Can you help me understand the problem? How can I reproduce the bug?

I see, well, in #552 the error is hydration error while withSSR is false. Another way to reproduce it is to put a console log in one main.tsx files, in the first condition (when the dataset.hydrate is true). And when running the project, remove the --with-ssr flag. At that point, we still hydrate and it will show the log.

If it's intentional, then for the 07_router ci test we need to consider another solution or remove the test completely since as it was commented there, the test was not supposed to work with ssr in standalone mode.

**Comment by dai-shi** [comment]
> for the 07_router ci test we need to consider another solution

After #565 is merged, is the test breaking? sorry, if I miss some points.

**Comment by Aslemammad** [comment]
> After https://github.com/dai-shi/waku/pull/565 is merged, is the test breaking? sorry, if I miss some points.

I haven't tried that PR yet, so let me try it and let you know.

**Review by dai-shi — CHANGES_REQUESTED** [review]
> the test was not supposed to work with ssr in standalone mode.

let's remove it.

**Comment by dai-shi** [comment]
Probably easier to create a new PR.

**Pull request closed without merging**
