### PR TITLE
feat: environment variables

### LINKED ISSUE #292: environment variables improvement
treat `WAKU_PUBLIC_` prefix as public env vars that can only be used in client side rendering (or ssr?)

others can be used in RSC

### PR DESCRIPTION
**Pull request by dai-shi**
close #292 

- [x] core
- [x] website
- [x] `.env.local`

### CODE REVIEW

**Comment by dai-shi** [comment]
I thought about using `import.meta.env` like Vite (and maybe use Vite feature), but it may not work well with server components. Thus, a global variable. We may revisit before v1.

Also, thought about using `dotenv`, but it's a naive one for now. We can consider depending on `dotenv` for more capabilities.

**Review by himself65 — COMMENTED** [review]
Can we re-use exsitingreact api?

https://react.dev/reference/react/experimental_taintUniqueValue

**Comment by dai-shi** [comment]
We can use it for safety when it's in `canary`.

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
I found a related vite issue: 

https://github.com/vitejs/vite/issues/9171

**Comment by dai-shi** [comment]
I was wondering if we could avoid optimized deps changes from the ground.

**Review by dai-shi — COMMENTED** [review]
Should be good.

**Comment by himself65** [comment]
How you do that

**Comment by dai-shi** [comment]
reviewed the breaking commit dbc3d29 and reverted some changes, and applied a new approach.

**Pull request merged**
