### PR TITLE
refactor: html-renderer and hander-dev

### PR DESCRIPTION
**Pull request by dai-shi**
which combines two vite instances.

### CODE REVIEW

**Comment by himself65** [comment]
I'm looking at this

**Review by himself65 — COMMENTED** [review]
```html
<html><head>
  <base href="/">
  <script type="module" async="">
globalThis.__waku_module_cache__ = new Map();
globalThis.__webpack_chunk_load__ = (id) => import(id).then((m) => globalThis.__waku_module_cache__.set(id, m));
globalThis.__webpack_require__ = (id) => globalThis.__waku_module_cache__.get(id);</script>

  <script type="module" async="">
import RefreshRuntime from "/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>

  <script type="module" src="/@vite/client"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="/src/main.tsx" async="" type="module"></script><title>Waku example</title><script>
globalThis.__WAKU_PREFETCHED__ = {
  '/RSC/index.txt': Promise.resolve(new Response(new ReadableStream({start(c) {const f = (s) => new TextEncoder().encode(decodeURI(s));globalThis.__WAKU_PUSH__ = (s) => s ? c.enqueue(f(s)) : c.close();}}))),
};
</script>  <script type="module">
import { createHotContext as __vite__createHotContext } from "/@vite/client";
import.meta.hot = __vite__createHotContext(import.meta.url);

if (import.meta.hot && !globalThis.__WAKU_HMR_CONFIGURED__) {
  globalThis.__WAKU_HMR_CONFIGURED__ = true;
  import.meta.hot.on('hot-import', (data) => import(/* @vite-ignore */ data));
  import.meta.hot.on('module', (data) => {
    // remove element with the same 'waku-module-id'
    let script = document.querySelector(
      'script[waku-module-id="' + data.id + '"]',
    );
    script?.remove();

    const code = data.code;
    script = document.createElement('script');
    script.type = 'module';
    script.text = code;
    script.setAttribute('waku-module-id', data.id);
    document.head.appendChild(script);
  });
}
</script>
</head><body><div style="border:3px red dashed;margin:1em;padding:1em"><h1 data-testid="app-name">Waku</h1><div data-testid="counter" style="border:3px blue dashed;margin:1em;padding:1em"><p data-testid="count">0</p><button data-testid="increment">Increment</button></div></div>
<script type="module" async="">globalThis.__WAKU_PUSH__("1:I%5B%22/@fs/C:/Users/himse/Code/waku/e2e/fixtures/ssr-basic/src/components/Counter.tsx%22,%5B%22/@fs/C:/Users/himse/Code/waku/e2e/fixtures/ssr-basic/src/components/Counter.tsx%22%5D,%22Counter%22%5D%0A0:%7B%22App%22:%5B%22$%22,%22div%22,null,%7B%22style%22:%7B%22border%22:%223px%20red%20dashed%22,%22margin%22:%221em%22,%22padding%22:%221em%22%7D,%22children%22:%5B%5B%22$%22,%22title%22,null,%7B%22children%22:%22Waku%20example%22%7D%5D,%5B%22$%22,%22h1%22,null,%7B%22data-testid%22:%22app-name%22,%22children%22:%22Waku%22%7D%5D,%5B%22$%22,%22$L1%22,null,%7B%7D%5D%5D%7D%5D%7D%0A")</script>
<script type="module" async="">globalThis.__WAKU_PUSH__()</script></body></html>
```

```html
<html><head>
  <base href="/">
  <script type="module" async="">
globalThis.__waku_module_cache__ = new Map();
globalThis.__webpack_chunk_load__ = (id) => import(id).then((m) => globalThis.__waku_module_cache__.set(id, m));
globalThis.__webpack_require__ = (id) => globalThis.__waku_module_cache__.get(id);</script>

  <script type="module" async="">
import RefreshRuntime from "/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>

  <script type="module" src="/@vite/client"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="/src/main.tsx" async="" type="module"></script><title>Waku example</title><script>
globalThis.__WAKU_PREFETCHED__ = {
  '/RSC/index.txt': Promise.resolve(new Response(new ReadableStream({start(c) {const f = (s) => new TextEncoder().encode(decodeURI(s));globalThis.__WAKU_PUSH__ = (s) => s ? c.enqueue(f(s)) : c.close();}}))),
};
</script>  <script type="module">
import { createHotContext as __vite__createHotContext } from "/@vite/client";
import.meta.hot = __vite__createHotContext(import.meta.url);

if (import.meta.hot && !globalThis.__WAKU_HMR_CONFIGURED__) {
  globalThis.__WAKU_HMR_CONFIGURED__ = true;
  import.meta.hot.on('hot-import', (data) => import(/* @vite-ignore */ data));
  import.meta.hot.on('module', (data) => {
    // remove element with the same 'waku-module-id'
    let script = document.querySelector(
      'script[waku-module-id="' + data.id + '"]',
    );
    script?.remove();

    const code = data.code;
    script = document.createElement('script');
    script.type = 'module';
    script.text = code;
    script.setAttribute('waku-module-id', data.id);
    document.head.appendChild(script);
  });
}
</script>
</head><body data-new-gr-c-s-check-loaded="14.1149.0" data-gr-ext-installed=""><script type="module" async="">globalThis.__WAKU_PUSH__("1:I%5B%22/@fs/C:/Users/himse/Code/waku/e2e/fixtures/ssr-basic/src/components/Counter.tsx%22,%5B%22/@fs/C:/Users/himse/Code/waku/e2e/fixtures/ssr-basic/src/components/Counter.tsx%22%5D,%22Counter%22%5D%0A0:%7B%22App%22:%5B%22$%22,%22div%22,null,%7B%22style%22:%7B%22border%22:%223px%20red%20dashed%22,%22margin%22:%221em%22,%22padding%22:%221em%22%7D,%22children%22:%5B%5B%22$%22,%22title%22,null,%7B%22children%22:%22Waku%20example%22%7D%5D,%5B%22$%22,%22h1%22,null,%7B%22data-testid%22:%22app-name%22,%22children%22:%22Waku%22%7D%5D,%5B%22$%22,%22$L1%22,null,%7B%7D%5D%5D%7D%5D%7D%0A")</script><script type="module" async="">globalThis.__WAKU_PUSH__()</script></body><grammarly-desktop-integration data-grammarly-shadow-root="true"></grammarly-desktop-integration></html>
```

**Review by himself65 — COMMENTED** [review]
```diff
Index: packages/waku/src/lib/renderers/html-renderer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/waku/src/lib/renderers/html-renderer.ts b/packages/waku/src/lib/renderers/html-renderer.ts
--- a/packages/waku/src/lib/renderers/html-renderer.ts	(revision 8404b457fb57a82faa83f363e073319435b1d59d)
+++ b/packages/waku/src/lib/renderers/html-renderer.ts	(date 1705126554030)
@@ -5,6 +5,7 @@
   FunctionComponent,
   ComponentProps,
 } from 'react';
+import type { ViteDevServer, InlineConfig } from 'vite';
 import type * as RDServerType from 'react-dom/server.edge';
 import type { default as RSDWClientType } from 'react-server-dom-webpack/client.edge';
 
@@ -31,6 +32,48 @@
 const moduleLoading = (globalThis as any).__webpack_module_loading__;
 const moduleCache = (globalThis as any).__webpack_module_cache__;
 
+type CreateViteServer = (
+  inlineConfig?: InlineConfig | undefined,
+) => Promise<ViteDevServer>;
+
+let lastViteServer: ViteDevServer | undefined;
+const getViteServer = async (createViteServer: CreateViteServer) => {
+  if (lastViteServer) {
+    return lastViteServer;
+  }
+  const { Server } = await import('node:http').catch((e) => {
+    // XXX explicit catch to avoid bundle time error
+    throw e;
+  });
+  const dummyServer = new Server(); // FIXME we hope to avoid this hack
+  // HACK to avoid bundling
+  const VITE_PLUGIN_REACT_VALUE = '@vitejs/plugin-react';
+  const VITE_PLUGIN_RSC_ENV_MODULE_VALUE = '../plugins/vite-plugin-rsc-env.js';
+  const { default: viteReact } = await import(VITE_PLUGIN_REACT_VALUE);
+  const { rscEnvPlugin } = await import(VITE_PLUGIN_RSC_ENV_MODULE_VALUE);
+  const viteServer = await createViteServer({
+    plugins: [viteReact(), rscEnvPlugin({})],
+    // HACK to suppress 'Skipping dependency pre-bundling' warning
+    optimizeDeps: { include: [] },
+    ssr: {
+      external: ['waku'],
+    },
+    appType: 'custom',
+    server: { middlewareMode: true, hmr: { server: dummyServer }, watch: null },
+  });
+  await viteServer.ws.close();
+  lastViteServer = viteServer;
+  return viteServer;
+};
+
+const loadServerFileDev = async (
+  fileURL: string,
+  createViteServer: CreateViteServer,
+) => {
+  const vite = await getViteServer(createViteServer);
+  return vite.ssrLoadModule(fileURLToFilePath(fileURL));
+};
+
 const fakeFetchCode = `
 Promise.resolve(new Response(new ReadableStream({
   start(c) {
@@ -211,11 +254,7 @@
     loadClientModule: (key: CLIENT_MODULE_KEY) => Promise<unknown>;
   } & (
     | { isDev: false; loadModule: EntriesPrd['loadModule']; isBuild: boolean }
-    | {
-        isDev: true;
-        rootDir: string;
-        loadServerFile: (fileURL: string) => Promise<unknown>;
-      }
+    | { isDev: true; createViteServer: CreateViteServer }
   ),
 ): Promise<ReadableStream | null> => {
   const {
@@ -252,6 +291,8 @@
   if (!ssrConfig) {
     return null;
   }
+  const rootDirDev =
+    isDev && (await getViteServer(opts.createViteServer)).config.root;
   let stream: ReadableStream;
   try {
     stream = await renderRscForHtml(
@@ -285,9 +326,12 @@
               const file = filePath.slice(config.basePath.length);
               // TODO too long, we need to refactor this logic
               if (isDev) {
+                if (!rootDirDev) {
+                  throw new Error('rootDirDev is not defined');
+                }
                 const filePath = file.startsWith('@fs/')
                   ? decodeFilePathFromAbsolute(file.slice('@fs'.length))
-                  : joinPath(opts.rootDir, file);
+                  : joinPath(rootDirDev, file);
                 const wakuDist = decodeFilePathFromAbsolute(
                   joinPath(fileURLToFilePath(import.meta.url), '../../..'),
                 );
@@ -309,7 +353,7 @@
                 if (!moduleLoading.has(id)) {
                   moduleLoading.set(
                     id,
-                    opts.loadServerFile(id).then((m) => {
+                    loadServerFileDev(id, opts.createViteServer).then((m) => {
                       moduleCache.set(id, m);
                     }),
                   );
Index: packages/waku/src/lib/handlers/handler-dev.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/waku/src/lib/handlers/handler-dev.ts b/packages/waku/src/lib/handlers/handler-dev.ts
--- a/packages/waku/src/lib/handlers/handler-dev.ts	(revision 8404b457fb57a82faa83f363e073319435b1d59d)
+++ b/packages/waku/src/lib/handlers/handler-dev.ts	(date 1705126535566)
@@ -4,11 +4,7 @@
 
 import { resolveConfig } from '../config.js';
 import type { Config } from '../config.js';
-import {
-  joinPath,
-  decodeFilePathFromAbsolute,
-  fileURLToFilePath,
-} from '../utils/path.js';
+import { joinPath, decodeFilePathFromAbsolute } from '../utils/path.js';
 import { endStream } from '../utils/stream.js';
 import { renderHtml } from '../renderers/html-renderer.js';
 import { decodeInput, hasStatusCode } from '../renderers/utils.js';
@@ -72,9 +68,6 @@
         rscHmrPlugin(),
         rscEnvPlugin({ config, hydrate: ssr }),
       ],
-      ssr: {
-        external: ['waku'],
-      },
       server: { middlewareMode: true },
     });
     const vite = await createViteServer(mergedViteConfig);
@@ -85,11 +78,6 @@
     return vite;
   });
 
-  const loadServerFile = async (fileURL: string) => {
-    const vite = await vitePromise;
-    return vite.ssrLoadModule(fileURLToFilePath(fileURL));
-  };
-
   const transformIndexHtml = async (pathname: string) => {
     const vite = await vitePromise;
     const encoder = new TextEncoder();
@@ -166,8 +154,7 @@
             getSsrConfigWithWorker(config, pathname, options),
           loadClientModule: (key) => import(CLIENT_MODULE_MAP[key]),
           isDev: true,
-          rootDir: vite.config.root,
-          loadServerFile,
+          createViteServer: (await import('vite')).createServer,
         });
         if (readable) {
           unstable_posthook?.(req, res, context as Context);

```

**Comment by himself65** [comment]
I reverted the refactor 2, ssr-basic works well. Not sure others

**Comment by dai-shi** [comment]
@himself65 Thanks for investing it. Reverting that commit is very unfortunate, because it is to combine the two vite instances, which should solve many issues going ahead. I wonder why it works on macos and ubuntu.

**Comment by dai-shi** [comment]
The error is
```
error: Not allowed to load local resource: file:///D:/a/waku/waku/e2e/fixtures/ssr-basic/src/components/Counter.tsx
```
but not sure how to fix...

https://vitejs.dev/config/server-options.html#server-fs-allow is not related, right?

**Comment by dai-shi** [comment]
looks like it's failing on macos too with `12_css`.

**Pull request merged**
