### PR TITLE
docs: add delpy button

### PR DESCRIPTION
**Pull request by himself65**

### CODE REVIEW

**Comment by dai-shi** [comment]
Is this still work in progress?

**Comment by himself65** [comment]
> Is this still work in progress?

yeah might be, I have one concern should this README.md and button included in the templates by `create-waku`

**Comment by dai-shi** [comment]
i don't think it's important to add it. @sandren ?

**Comment by sandren** [comment]
> i don't think it's important to add it. @sandren ?

I don't think it's necessary.

**Pull request closed without merging**
