### PR TITLE
experimental: use serverless for website

### PR DESCRIPTION
**Pull request by dai-shi**

### CODE REVIEW

**Review by himself65 — CHANGES_REQUESTED** [review]
I got a blank page

https://waku-git-website-with-serverless-daishis-projects.vercel.app/non-exist

**Comment by dai-shi** [comment]
oh, that's interesting, not expected.

**Comment by dai-shi** [comment]
Hmm, I don't know how it happens (to be `200` instead of `404`).
Help wanted.

**Comment by himself65** [comment]
Add some log, found issue
image

**Comment by himself65** [comment]
> What's the issue??

ctx.res === undefined

**Comment by dai-shi** [comment]
> > What's the issue??
> 
> ctx.res === undefined

But, then it should be handled by `app.notFound`, no? At least, `waku start` on localhost works fine.

**Comment by rmarscher** [comment]
> But, then it should be handled by `app.notFound`, no? At least, `waku start` on localhost works fine.

I'm having a similar 404 issue on my cloudflare pages deploy. I have a console.log in app.notFound and verified it runs. Something must modify the response or the ctx after that. https://fc7720e6.waku-test.pages.dev/asdf

If you build the project and then run the dist output instead of the vite dev server, you should be able to reproduce it locally. I'm going to see if I can set up a step debugger to figure it out.

**Comment by dai-shi** [comment]
Fixed by #796.

**Pull request closed without merging**
