### PR TITLE
refactor(waku): prettify cli using commander.js

### PR DESCRIPTION
**Pull request by himself65**
now the CLI has growing complex, I think we need a standard library to handle the thing

### CODE REVIEW

**Comment by dai-shi** [comment]
> now the CLI has growing complex, I think we need a standard library to handle the thing

Yeah, I was thinking about it too. But, I have a few concerns:
- The diff doesn't seem to improve so much. Maybe it's too early at this point.
- I used commander.js before, and found it somewhat traditional. Is it still widely used?
- It must be an optional peer dependency and it requires to add a dependency in the templates. That's a huge motivation to avoid using libraries unless it's very helpful.

**Comment by himself65** [comment]
> > now the CLI has growing complex, I think we need a standard library to handle the thing
> 
> Yeah, I was thinking about it too. But, I have a few concerns:
> 
> * The diff doesn't seem to improve so much. Maybe it's too early at this point.
> * I used commander.js before, and found it somewhat traditional. Is it still widely used?
> * It must be an optional peer dependency and it requires to add a dependency in the templates. That's a huge motivation to avoid using libraries unless it's very helpful.

There are some options:

arg: https://github.com/huozhi/bunchee/blob/main/src/bin/index.ts
commander.js: https://github.com/vercel/next.js/blob/canary/packages/create-next-app/index.ts
clipanion: https://github.com/napi-rs/napi-rs/blob/main/cli/src/cli.ts

**Comment by himself65** [comment]
https://www.npmjs.com/package/meow

**Comment by dai-shi** [comment]
Thanks.

I would like to hold this for the moment, and revisit it in the future. There might be more hidden requirements in cli.ts and we can't decide it now.

**Comment by dai-shi** [comment]
> It must be an optional peer dependency and it requires to add a dependency in the templates. That's a huge motivation to avoid using libraries unless it's very helpful.

This limitation is gone with #355.

**Comment by dai-shi** [comment]
I'm still interested in using commander.js or some alternatives (maybe commander.js is fine.)

Maybe some time later, maybe before v1-alpha. Let's start over anyway.

**Comment by dai-shi** [comment]
#1319 should be a follow-up.

**Pull request closed without merging**
