### PR TITLE
fix(handler): return promise of stream with allReady

### PR DESCRIPTION
**Pull request by dai-shi**
Fixes #1082 
Reverts #1078

### CODE REVIEW

**Comment by dai-shi** [comment]
I think we can revert #1078 with this change. cc @rmarscher

**Comment by rmarscher** [comment]
> I think we can revert #1078 with this change. cc @rmarscher

allReady waits for all of the suspense boundaries to render. #1078 just waits for the first chunk to start sending. They are not the same. I think it's best to keep the waitForFirstByte to allow more flexibility with running server-side code before the first suspense boundary.

**Comment by dai-shi** [comment]
> > I think we can revert #1078 with this change. cc @rmarscher
> 
> allReady waits for all of the suspense boundaries to render. #1078 just waits for the first chunk to start sending. They are not the same. I think it's best to keep the waitForFirstByte to allow more flexibility with running server-side code before the first suspense boundary.

I understand it's not the same, but `waitForFirstChunk` is very limited either.
Isn't it correct that `handler` now behaves like how `rsc`/`ssr` did previously?

---

If `waitForFirstChunk` is truly what peopole want, I think it can be implemented with a separate middleware.

**Comment by rmarscher** [comment]
> Isn't it correct that `handler` now behaves like how `rsc`/`ssr` did previously?

Ah, ok. Yes. I just tested with v0.21.10. This is great. The handleRequest promise now waits on the 
initial entry layout and page render functions. If I add a suspense boundary to a layout, it will send the outer shell when it is ready. Perfect.

**Pull request merged**
