### PR TITLE
Update react canary

### PR DESCRIPTION
**Pull request by dai-shi**

### CODE REVIEW

**Comment by dai-shi** [comment]
it works without ssr, but keep it for now.
```diff
diff --git a/packages/website/package.json b/packages/website/package.json
index 6520efc..a0f7965 100644
--- a/packages/website/package.json
+++ b/packages/website/package.json
@@ -5,7 +5,7 @@
   "type": "module",
   "private": true,
   "scripts": {
-    "dev": "waku dev --with-ssr",
+    "dev": "waku dev",
     "build": "waku build --with-ssr",
     "start": "waku start --with-ssr"
   },
```

**Comment by dai-shi** [comment]
it has such an e2e test. 😓

**Comment by dai-shi** [comment]
All fixed including the issue I noted above.

**Comment by ryota-murakami** [comment]
@dai-shi Where latest canary release changelog are you getting from?
And [packages/waku/src/client.ts](https://github.com/dai-shi/waku/pull/399/files#diff-cca6c693e8e770d08e60eae7af6534fadb99e5acf1af470a20f2d28bee2ade58) change is for fix breaking via update canary version?

**Comment by dai-shi** [comment]
here: https://github.com/facebook/react/compare/c5b937576...b30030471
And yes.

**Comment by ryota-murakami** [comment]
@dai-shi Thanks, I learned canary versioning id is just a commit hash. 😅

**Pull request merged**
