### PR TITLE
fix: document overflow

### PR DESCRIPTION
**Pull request by himself65**
See https://waku.gg/practices/minimal and scroll to the bottom

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks!
Oh, but this doesn't work if the width is small.
image

And, I realized that it doesn't support mobile anyway.

**Comment by dai-shi** [comment]
Added viewport 9b43dd5 in main. Please merge.

**Comment by Himself65** [comment]
> Added viewport [9b43dd5](https://github.com/dai-shi/waku/commit/9b43dd5cc487f2a16a63655b1ef3da018c153913) in main. Please merge.

rebased!

**Comment by Himself65** [comment]
Could you please turn on this feature so that we can merge the branch by clicking button

image

**Comment by dai-shi** [comment]
Done!

**Review by dai-shi — CHANGES_REQUESTED** [review]
Can you support mobile size screen?

https://github.com/dai-shi/waku/assets/490574/8ad8e47a-6f8c-499d-bad4-0cac6455ec69

**Comment by himself65** [comment]
I think https://github.com/dai-shi/waku/pull/82 covers my stuff. Closing

**Pull request closed without merging**
