### PR TITLE
chore: HMRBroadcaster

### PR DESCRIPTION
**Pull request by Aslemammad**
An attempt to get https://github.com/vitejs/vite-ecosystem-ci/pull/330 done!

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
This change alone looks reasonable.

**Comment by Aslemammad** [comment]
feel free to have a look on the discord thread!

**Comment by tylersayshi** [comment]
> feel free to have a look on the discord thread!

@Aslemammad is this the thread you are referencing? 

[discord link](https://discord.com/channels/804011606160703521/928398470086291456/1300767997207646279)

**Comment by Aslemammad** [comment]
> @Aslemammad is this the thread you are referencing?

Oh no, I meant a private thread we had with @dai-shi 😅

**Review by dai-shi — APPROVED** [review]

**Pull request merged**
