### PR TITLE
feat(router): createPages

### LINKED ISSUE #246: re-design waku/router
notes:
- waku minimal API for library authors and waku/router for app developers
- we need `exists(pathStr)` in defineRouter
- base API for libraries, config-based API and file-based API?

### PR DESCRIPTION
**Pull request by dai-shi**
Close #246

### CODE REVIEW

**Comment by Aslemammad** [comment]
Why not the traditional file-based routing? Just curious.

**Comment by dai-shi** [comment]
config-based router matches better for non-node env and for vite/rollup limitation.
We (including third-party library authors) can create a file-based router too.

**Comment by himself65** [comment]
```
chunk-43D56K65.js?v=0b716eb3:517 Warning: Expected server HTML to contain a matching <div> in <body>.
    at div
    at Slot (http://localhost:3000/@fs/C:/Users/himse/Code/waku/packages/waku/dist/client.js:85:24)
    at Children (http://localhost:3000/@fs/C:/Users/himse/Code/waku/packages/waku/dist/client.js:98:29)
    at Slot (http://localhost:3000/@fs/C:/Users/himse/Code/waku/packages/waku/dist/client.js:85:24)
    at InnerRouter (http://localhost:3000/@fs/C:/Users/himse/Code/waku/packages/waku/dist/router/client.js:93:24)
    at Root (http://localhost:3000/@fs/C:/Users/himse/Code/waku/packages/waku/dist/client.js:65:24)
    at Router (http://localhost:3000/@fs/C:/Users/himse/Code/waku/packages/waku/dist/router/client.js:187:26)
    at ErrorBoundaryClass (http://localhost:3000/src/components/ErrorBoundary.tsx:4:5)
printWarning @ chunk-43D56K65.js?v=0b716eb3:517
Show 1 more frame
Show less
chunk-43D56K65.js?v=0b716eb3:5811 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (chunk-43D56K65.js?v=0b716eb3:5811:17)
    at tryToClaimNextHydratableInstance (chunk-43D56K65.js?v=0b716eb3:5847:15)
    at updateHostComponent$1 (chunk-43D56K65.js?v=0b716eb3:12330:13)
    at beginWork$1 (chunk-43D56K65.js?v=0b716eb3:13544:22)
    at HTMLUnknownElement.callCallback2 (chunk-43D56K65.js?v=0b716eb3:14856:22)
    at Object.invokeGuardedCallbackImpl (chunk-43D56K65.js?v=0b716eb3:14881:24)
    at invokeGuardedCallback (chunk-43D56K65.js?v=0b716eb3:14921:37)
    at beginWork (chunk-43D56K65.js?v=0b716eb3:18955:15)
    at performUnitOfWork (chunk-43D56K65.js?v=0b716eb3:18240:20)
    at workLoopSync (chunk-43D56K65.js?v=0b716eb3:18066:13)
chunk-43D56K65.js?v=0b716eb3:517 Warning: An error occurred during hydration. The server HTML was replaced with client content in <body>.
printWarning @ chunk-43D56K65.js?v=0b716eb3:517
Show 1 more frame
Show less
chunk-43D56K65.js?v=0b716eb3:17611 Uncaught Error: Unknown root exit status.
    at finishConcurrentRender (chunk-43D56K65.js?v=0b716eb3:17611:21)
    at performConcurrentWorkOnRoot (chunk-43D56K65.js?v=0b716eb3:17552:17)
    at workLoop (chunk-43D56K65.js?v=0b716eb3:191:42)
    at flushWork (chunk-43D56K65.js?v=0b716eb3:170:22)
```

**Comment by dai-shi** [comment]
Thanks.

Why hydration mismatch only on windows...

**Review by himself65 — CHANGES_REQUESTED** [review]
```diff
Subject: [PATCH] fix: add suspense
---
Index: packages/waku/src/router/client.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/waku/src/router/client.ts b/packages/waku/src/router/client.ts
--- a/packages/waku/src/router/client.ts	(revision 7d50ea37986f14e884897c1af0e156db40bb824d)
+++ b/packages/waku/src/router/client.ts	(date 1703307050084)
@@ -10,6 +10,7 @@
   useState,
   useTransition,
   Fragment,
+  Suspense,
 } from 'react';
 import type { ComponentProps, FunctionComponent, ReactNode } from 'react';
 
@@ -224,13 +225,17 @@
   );
 
   return createElement(
-    Fragment,
-    null,
-    createElement(Slot, { id: SHOULD_SKIP_ID }),
-    createElement(
-      RouterContext.Provider,
-      { value: { loc, changeLocation, prefetchLocation } },
-      children,
+    Suspense,
+    null,
+    createElement(
+      Fragment,
+      null,
+      createElement(Slot, { id: SHOULD_SKIP_ID }),
+      createElement(
+        RouterContext.Provider,
+        { value: { loc, changeLocation, prefetchLocation } },
+        children,
+      ),
     ),
   );
 }
```

**Comment by himself65** [comment]
> ```diff
> Subject: [PATCH] fix: add suspense
> ---
> Index: packages/waku/src/router/client.ts
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/packages/waku/src/router/client.ts b/packages/waku/src/router/client.ts
> --- a/packages/waku/src/router/client.ts	(revision 7d50ea37986f14e884897c1af0e156db40bb824d)
> +++ b/packages/waku/src/router/client.ts	(date 1703307050084)
> @@ -10,6 +10,7 @@
>    useState,
>    useTransition,
>    Fragment,
> +  Suspense,
>  } from 'react';
>  import type { ComponentProps, FunctionComponent, ReactNode } from 'react';
>  
> @@ -224,13 +225,17 @@
>    );
>  
>    return createElement(
> -    Fragment,
> -    null,
> -    createElement(Slot, { id: SHOULD_SKIP_ID }),
> -    createElement(
> -      RouterContext.Provider,
> -      { value: { loc, changeLocation, prefetchLocation } },
> -      children,
> +    Suspense,
> +    null,
> +    createElement(
> +      Fragment,
> +      null,
> +      createElement(Slot, { id: SHOULD_SKIP_ID }),
> +      createElement(
> +        RouterContext.Provider,
> +        { value: { loc, changeLocation, prefetchLocation } },
> +        children,
> +      ),
>      ),
>    );
>  }
> ```

This will fix, but hydration error still

**Comment by dai-shi** [comment]
btw, I don't know how the windows CI failing issue was resolved.

**Pull request merged**
